name: cratermaker
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - numpy>=1.22
  - scipy>=1.11.3
  - xarray>=2024.1
  - uxarray>=2024.2
  - numba>=0.58.1
  - holoviews>=1.18.1
  - cartopy>=0.22.0
  - dask>=2023.12.1
  - datashader>=0.16.0
  - scikit-learn>=1.3.2
  - cython>=3.0.0
  - matplotlib>=3.8.2
  - netCDF4>=1.6.5
  - matplotlib>=3.8.2
  - scikit-build-core>=0.7.0
  - pytest
  - cmake
  - libnetcdf 
  - jigsaw>=0.9
  - jigsawpy
  - mpas_tools>=0.29
  - gfortran>=13.2
  - pip>=20.1 
  - pip:
    - -no-build-isolation -e .
